version: '3.8'

services:
  db:
    image: mysql:8.0
    platform: linux/arm64/v8
    restart: always
    environment:
      MYSQL_DATABASE: 'agro'
      MYSQL_USER: 'agro'
      MYSQL_PASSWORD: 'agro'
      MYSQL_ROOT_PASSWORD: 'agro'
      
      MYSQL_ROOT_HOST: '%'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
